#!/bin/bash
# Script to change file permissions for website

chown www-data:www-data /home/koekwo/WebSites/Prj_Dja_Dev_Auto/cardisplay/db.sqlite3
chmod 665 /home/koekwo/WebSites/Prj_Dja_Dev_Auto/cardisplay/db.sqlite3
chown -R www-data:www-data /home/koekwo/WebSites/Prj_Dja_Dev_Auto/cardisplay
chown -R www-data:www-data /home/koekwo/WebSites/Prj_Dja_Dev_Auto/cardisplay/media_root
chmod 775 /home/koekwo/WebSites/Prj_Dja_Dev_Auto/cardisplay/media_root
