# Generated by Django 3.0.5 on 2022-06-01 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_VoorNm', models.CharField(max_length=45, verbose_name='Voornaam')),
                ('cnt_AchterNm', models.CharField(max_length=65, verbose_name='Achternaam')),
                ('cnt_TussenVgsl', models.CharField(max_length=15, verbose_name='Tussenvoegsel')),
                ('cnt_VoorLtrs', models.CharField(max_length=10, verbose_name='Voorletters')),
                ('cnt_Notities', models.TextField(verbose_name='Notities')),
            ],
        ),
        migrations.CreateModel(
            name='Nummer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmb_Number', models.CharField(help_text='Mobiel, Telefoon, E-mail, Facebook, enz.', max_length=85, verbose_name='Nummer')),
                ('nmb_Medium', models.CharField(choices=[('M', 'Mobiel nummer'), ('H', 'Huistelefoon'), ('E', 'E-Mail'), ('F', 'Fax'), ('A', 'Facebook'), ('L', 'LinkedIn'), ('T', 'Twitter')], max_length=1, verbose_name='Medium')),
                ('nmb_Notities', models.CharField(help_text='Kanttekening bij dit medium', max_length=120, verbose_name='Notitie')),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drzData.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr_Straat', models.CharField(max_length=100, verbose_name='Straat')),
                ('adr_HuisNr', models.CharField(max_length=10, verbose_name='Huisnummer')),
                ('adr_HuisNrToev', models.CharField(max_length=10, verbose_name='Toevoeging')),
                ('adr_PostCd', models.CharField(max_length=15, verbose_name='Postcode')),
                ('adr_Plaats', models.CharField(max_length=85, verbose_name='Plaats')),
                ('adr_type', models.CharField(choices=[('W', 'Woonadres'), ('B', 'Bezoekadres'), ('A', 'Afleveradres'), ('V', 'Verblijfadres')], max_length=1)),
                ('adr_Notities', models.TextField(verbose_name='Notities')),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drzData.Contact')),
            ],
            options={
                'verbose_name_plural': 'Adressen',
            },
        ),
    ]
