# Generated by Django 3.2.5 on 2022-07-08 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aci_Naam', models.CharField(max_length=85, verbose_name='Naam')),
                ('aci_Omschr', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
                ('aci_Status', models.CharField(blank=True, choices=[('O', 'Open'), ('U', 'In Uitvoering'), ('V', 'Volbracht')], default='O', max_length=1, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Acties',
            },
        ),
        migrations.CreateModel(
            name='Activiteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_Naam', models.CharField(help_text='Naam van de activiteit, project of themadag', max_length=85, verbose_name='Naam / Titel')),
                ('act_Omschr', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
                ('act_Type', models.CharField(blank=True, choices=[('L', 'Lezing'), ('E', 'Excursie'), ('T', 'Thema-avond'), ('E', 'Project'), ('E', 'Excursie')], default='L', max_length=1, null=True, verbose_name='Type activiteit')),
            ],
            options={
                'verbose_name': 'Activiteit, Project, Lezing, enz.',
                'verbose_name_plural': 'Activiteiten',
            },
        ),
        migrations.CreateModel(
            name='Bezoekreden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bzr_Naam', models.CharField(max_length=120, verbose_name='Reden')),
                ('bzr_Omschr', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
            ],
            options={
                'verbose_name_plural': 'Bezoekredenen',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_VoorNm', models.CharField(max_length=45, verbose_name='Voornaam')),
                ('cnt_AchterNm', models.CharField(max_length=65, verbose_name='Achternaam')),
                ('cnt_TussenVgsl', models.CharField(blank=True, max_length=15, null=True, verbose_name='Tussenvoegsel')),
                ('cnt_VoorLtrs', models.CharField(blank=True, max_length=10, null=True, verbose_name='Voorletters')),
                ('cnt_Notities', models.TextField(blank=True, null=True, verbose_name='Notities')),
                ('cnt_Type', models.CharField(blank=True, choices=[('W', 'Winkelklant'), ('H', 'Huisbezoek')], default='W', max_length=1, null=True, verbose_name='Type contact')),
                ('cnt_Acties', models.ManyToManyField(blank=True, help_text='Acties (open) mbt dit contact; ', related_query_name='acties_related', to='drzData.Actie', verbose_name='Acties')),
            ],
            options={
                'verbose_name_plural': 'Contacten',
                'ordering': ('cnt_AchterNm', 'cnt_VoorNm'),
            },
        ),
        migrations.CreateModel(
            name='Groep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_GroupNm', models.CharField(max_length=45, verbose_name='Groep')),
                ('grp_Website', models.CharField(blank=True, help_text='Plak hier de url van website van groep', max_length=240, null=True, verbose_name='Website')),
                ('grp_Notities', models.TextField(blank=True, null=True, verbose_name='Notities')),
                ('grp_Type', models.CharField(blank=True, choices=[('B', 'Bedrijf'), ('I', 'Instantie'), ('S', 'Stichting'), ('O', 'Organisatie'), ('G', 'Gemeente'), ('R', 'Rijksoverheid'), ('A', 'Afdeling')], default='O', max_length=1, null=True, verbose_name='Type groep')),
            ],
            options={
                'verbose_name': 'Groep',
                'verbose_name_plural': 'Organisaties, Instanties, Bedrijven, enz.',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_Naam', models.CharField(max_length=85, verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='AdviesContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drzData.contact')),
                ('cnt_DatVastlegging', models.DateTimeField(blank=True, null=True, verbose_name='Tijdstip van notatie')),
                ('cnt_NieuwsBrief', models.BooleanField(blank=True, default=False, help_text='Dit aanvinken als het contact de nieuwsbrief wil ontvangen', null=True, verbose_name='Nieuwbrief')),
                ('cnt_Activiteit', models.ManyToManyField(blank=True, help_text='Activiteiten waaraan dit contact deelneemt; ', to='drzData.Activiteit', verbose_name='Activiteiten')),
                ('cnt_Vastlegger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='Genoteerd door', to=settings.AUTH_USER_MODEL, verbose_name='Vastlegger')),
            ],
            options={
                'verbose_name_plural': 'Contacten',
                'ordering': ('cnt_AchterNm', 'cnt_VoorNm'),
            },
            bases=('drzData.contact',),
        ),
        migrations.CreateModel(
            name='Exposant',
            fields=[
                ('groep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drzData.groep')),
                ('exp_Verhaal', models.TextField(blank=True, null=True, verbose_name='Verhaal')),
            ],
            options={
                'verbose_name_plural': 'Exposanten',
            },
            bases=('drzData.groep',),
        ),
        migrations.CreateModel(
            name='WinkelBezoek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbz_TijdStip', models.DateTimeField(blank=True, null=True, verbose_name='Tijdstip van bezoek')),
                ('wbz_Notities', models.TextField(blank=True, null=True, verbose_name='Notities')),
                ('wbz_Bezoeken', models.ManyToManyField(blank=True, to='drzData.Bezoekreden', verbose_name='Bezoekreden(en)')),
            ],
            options={
                'verbose_name_plural': 'Winkelbezoeken',
                'ordering': ('wbz_TijdStip',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvw_Tekst', models.TextField(verbose_name='Reviewtekst')),
                ('rvw_Beoordeling', models.CharField(blank=True, choices=[('Z', 'Zeer Goed'), ('G', 'Goed'), ('V', 'Voldoende'), ('S', 'Slecht'), ('E', 'Zeer Slecht')], max_length=1, null=True, verbose_name='Medium')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.product')),
            ],
        ),
        migrations.CreateModel(
            name='Nummer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmb_Number', models.CharField(help_text='Mobiel, Telefoon, E-mail, Facebook, enz.', max_length=85, verbose_name='Nummer')),
                ('nmb_Medium', models.CharField(blank=True, choices=[('M', 'Mobiel nummer'), ('H', 'Huistelefoon'), ('E', 'E-Mail'), ('F', 'Fax'), ('A', 'Facebook'), ('L', 'LinkedIn'), ('T', 'Twitter')], max_length=1, null=True, verbose_name='Medium')),
                ('nmb_Notities', models.CharField(blank=True, max_length=120, null=True, verbose_name='Notitie')),
                ('Contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.contact')),
                ('Groep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.groep')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_Groepen',
            field=models.ManyToManyField(blank=True, help_text='Groepen waaronder dit contact valt; ', to='drzData.Groep', verbose_name='Groep(en)'),
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr_Straat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Straat')),
                ('adr_HuisNr', models.CharField(blank=True, max_length=10, null=True, verbose_name='Huisnummer')),
                ('adr_HuisNrToev', models.CharField(blank=True, max_length=10, null=True, verbose_name='Toevoeging')),
                ('adr_PostCd', models.CharField(blank=True, max_length=15, null=True, verbose_name='Postcode')),
                ('adr_Plaats', models.CharField(blank=True, max_length=85, null=True, verbose_name='Plaats')),
                ('adr_type', models.CharField(blank=True, choices=[('W', 'Woonadres'), ('B', 'Bezoekadres'), ('A', 'Afleveradres'), ('V', 'Verblijfadres')], default='W', max_length=1, null=True, verbose_name='Type adres')),
                ('adr_Notities', models.TextField(blank=True, null=True, verbose_name='Notities')),
                ('Contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.contact')),
                ('Groep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.groep')),
            ],
            options={
                'verbose_name_plural': 'Adressen',
            },
        ),
        migrations.CreateModel(
            name='Woninggegevens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wng_TypeWoning', models.CharField(blank=True, choices=[('T', 'Tussenwoning'), ('H', 'Hoekwoning'), ('2', '2-1 Kap'), ('V', 'Vrijstaand'), ('A', 'Appartement')], max_length=1, null=True, verbose_name='Type Woning')),
                ('wng_Bouwjaar', models.CharField(blank=True, choices=[('V', 'Voor 1980'), ('T', '1980 - 2000'), ('N', 'Na 2000')], max_length=1, null=True, verbose_name='Bouwjaar')),
                ('wng_Bewoning', models.CharField(blank=True, choices=[('H', 'Verhuur'), ('V', 'VVE'), ('E', 'Eigendom')], max_length=1, null=True, verbose_name='Type bewoning')),
                ('Contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.adviescontact')),
            ],
            options={
                'verbose_name_plural': 'Woninggegevens',
            },
        ),
        migrations.CreateModel(
            name='Vraag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrg_TypeVraag', models.CharField(blank=True, choices=[('I', 'Info'), ('A', 'Advies'), ('O', 'Offerte')], max_length=1, null=True, verbose_name='Type vraag')),
                ('vrg_OnderwerpVraag', models.CharField(blank=True, choices=[('Ea', 'Energie algemeen'), ('Eiv', 'Energie isolatie vloer'), ('Eim', 'Energie isolatie muur'), ('Eig', 'Energie isolatie glas'), ('Eid', 'Energie isolatie dak'), ('Ev', 'Energie verwarming'), ('Eo', 'Energie opwekking'), ('C', 'Circulair'), ('G', 'Groen'), ('O', 'Overig')], max_length=3, null=True, verbose_name='Onderwerp vraag')),
                ('vrg_StatusVraag', models.CharField(blank=True, choices=[('B', 'Beantwoord'), ('O', 'Onbeantwoord'), ('U', 'Wordt uitgezocht')], max_length=1, null=True, verbose_name='Status vraag')),
                ('vrg_Tekst', models.TextField(blank=True, null=True, verbose_name='Tekst vraag')),
                ('Contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.adviescontact')),
            ],
            options={
                'verbose_name_plural': 'Vragen',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Exposant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.exposant'),
        ),
    ]
