# Generated by Django 3.0.5 on 2022-06-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacten'},
        ),
        migrations.AlterField(
            model_name='adres',
            name='adr_HuisNr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Huisnummer'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='adr_HuisNrToev',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Toevoeging'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='adr_Notities',
            field=models.TextField(blank=True, null=True, verbose_name='Notities'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='adr_Plaats',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='Plaats'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='adr_PostCd',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='adr_Straat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Straat'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='adr_type',
            field=models.CharField(blank=True, choices=[('W', 'Woonadres'), ('B', 'Bezoekadres'), ('A', 'Afleveradres'), ('V', 'Verblijfadres')], default='W', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cnt_Notities',
            field=models.TextField(blank=True, null=True, verbose_name='Notities'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cnt_TussenVgsl',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tussenvoegsel'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cnt_VoorLtrs',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Voorletters'),
        ),
        migrations.AlterField(
            model_name='nummer',
            name='nmb_Medium',
            field=models.CharField(blank=True, choices=[('M', 'Mobiel nummer'), ('H', 'Huistelefoon'), ('E', 'E-Mail'), ('F', 'Fax'), ('A', 'Facebook'), ('L', 'LinkedIn'), ('T', 'Twitter')], max_length=1, null=True, verbose_name='Medium'),
        ),
        migrations.AlterField(
            model_name='nummer',
            name='nmb_Notities',
            field=models.CharField(blank=True, help_text='Kanttekening bij dit medium', max_length=120, null=True, verbose_name='Notitie'),
        ),
    ]
