# Generated by Django 3.2.5 on 2022-07-22 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0002_auto_20220722_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachgesprek',
            options={'verbose_name_plural': 'Coachgesprekken'},
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_OverigOpmerk_Slk',
            field=models.TextField(blank=True, null=True, verbose_name='Overige opmerkingen slaapkamer(s)'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_AanmeldAnders',
            field=models.TextField(blank=True, help_text='Vermeld hier andere reden voor aanmelding', null=True, verbose_name='Anders'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_AanmeldingWoonCorp',
            field=models.CharField(blank=True, choices=[('V', 'Verhuizing'), ('P', 'Plaatsing nieuwe apparatuur'), ('K', 'Na een klacht'), ('Ko', 'Kleinschalig onderhoud'), ('Go', 'Grootschalig onderhoud'), ('On', 'Oplevering nieuwbouw')], help_text='De reden van aanmelding indien aangemeld via wooncooperatie', max_length=2, null=True, verbose_name='Aanmeldingsrede Wooncooperatie'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_AanmeldingZelf',
            field=models.CharField(blank=True, choices=[('W', 'Website'), ('S', 'Social media'), ('M', 'Mailing'), ('B', 'Bewonersavond'), ('Wa', 'Wijkactie'), ('Vc', 'Verwijzing consulent'), ('Vb', 'Verwijzing mede-huurders')], help_text='De reden van aanmelding indien zelf aangemeld', max_length=2, null=True, verbose_name='Zelf aangemeld'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_AdviesContact',
            field=models.OneToOneField(blank=True, help_text='Kies bijbehorende adviescontact', null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.adviescontact', verbose_name='Adviescontact'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_OverigOpmerk_Gng',
            field=models.TextField(blank=True, null=True, verbose_name='Overige opmerkingen gang'),
        ),
    ]
