# Generated by Django 3.2.5 on 2022-07-28 15:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0002_alter_coachgesprek_cgs_aanmeldingwooncorp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_AanmeldingZelf',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('W', 'Website'), ('S', 'Social media'), ('M', 'Mailing'), ('B', 'Bewonersavond'), ('Wa', 'Wijkactie'), ('Vc', 'Verwijzing consulent'), ('Vb', 'Verwijzing mede-huurders')], help_text='De reden van aanmelding indien zelf aangemeld', max_length=16, null=True, verbose_name='Zelf aangemeld'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_AanwApperatuur',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('T', 'Thuistap'), ('Wk', 'Waterkoker'), ('Km', 'Keukenmachine'), ('Ka', 'Koffiezetapparaat'), ('Br', 'Broodrooster'), ('Cg', 'Contact grill')], help_text='Overige aanwezige apperatuur', max_length=16, null=True, verbose_name='Aanwezige apparatuur'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_Motivatie',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ml', 'Verlagen maandlasten'), ('C', 'Confort verbeteren'), ('L', 'Leuke uitdaging'), ('G', 'Gezondheid'), ('M', 'Iets voor het milieu doen'), ('A', 'Niet achter willen blijven'), ('Vl', 'Voorop willen lopen')], help_text='Wat is de motivatie voor de aanvraag?', max_length=15, null=True, verbose_name='Motivatie'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_Problemen_K',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'Schimmel'), ('V', 'Vocht'), ('G', 'Geluid')], help_text='Constateerd u problemen in de keuken?', max_length=5, null=True, verbose_name='Problemen keuken'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_Problemen_Slk',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'Schimmel'), ('V', 'Vocht'), ('G', 'Geluid')], help_text='Constateerd u problemen in de slaapkamer?', max_length=5, null=True, verbose_name='Problemen slaapkamer'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_Problemen_Wk',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'Schimmel'), ('V', 'Vocht'), ('G', 'Geluid')], help_text='Constateerd u problemen in de woonkamer?', max_length=5, null=True, verbose_name='Problemen woonkamer'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeBed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Geen'), ('W', 'Waterbed'), ('E', 'Elektrische deken')], max_length=5, null=True, verbose_name='Type bedverwarming'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeRaambekleding_Wk',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Gordijn'), ('J', 'Jaloezie'), ('V', 'Vouwgordijnen'), ('R', 'Rolgordijnen')], help_text='Type raambekleding in de woonkamer?', max_length=7, null=True, verbose_name='Type raambekleding'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeRadiatorknop',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Gewoon'), ('T', 'Thermostaat')], help_text='Type radiatorknoppen aanwezig in huis?', max_length=3, null=True, verbose_name='Type radiatorknop'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeTochtVoorziening_Gng',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Geen'), ('Ts', 'Tochtstrip'), ('K', 'Kussen')], max_length=6, null=True, verbose_name='Type tochtvoorziening gang'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeVerlichting_Gng',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Gloeilamp'), ('T', 'TL'), ('H', 'Halogeen'), ('L', 'Led')], help_text='Wat voor type verlichting is er aanwezig in de Gang?', max_length=7, null=True, verbose_name='Type verlichting in gang'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeVerlichting_Slk',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Gloeilamp'), ('T', 'TL'), ('H', 'Halogeen'), ('L', 'Led')], max_length=7, null=True, verbose_name='Type verlichting slaapkamer'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeVerlichting_Wk',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Gloeilamp'), ('T', 'TL'), ('H', 'Halogeen'), ('L', 'Led')], help_text='Wat voor type verlichting is er aanwezig in de woonkamer?', max_length=7, null=True, verbose_name='Type verlichting'),
        ),
    ]
