# Generated by Django 3.2.5 on 2022-06-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0002_auto_20220619_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_Naam', models.CharField(help_text='Naam van de activiteit, project of themadag', max_length=85, verbose_name='Naam / Titel')),
                ('act_Omschr', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
                ('act_Type', models.CharField(blank=True, choices=[('L', 'Lezing'), ('E', 'Excursie'), ('T', 'Thema-avond'), ('E', 'Project'), ('E', 'Excursie')], default='L', max_length=1, null=True, verbose_name='Type activiteit')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('cnt_AchterNm', 'cnt_VoorNm'), 'verbose_name_plural': 'Contacten'},
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_NieuwsBrief',
            field=models.BooleanField(blank=True, default=False, help_text='Dit aanvinken als het contact de nieuwsbrief wil ontvangen', null=True, verbose_name='Nieuwbrief'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_Type',
            field=models.CharField(blank=True, choices=[('W', 'Winkelklant'), ('H', 'Huisbezoek')], default='W', max_length=1, null=True, verbose_name='Type contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_Activiteit',
            field=models.ManyToManyField(blank=True, help_text='Activiteiten waaraan dit contact deelneemt', to='drzData.Activiteit', verbose_name='Activiteiten'),
        ),
    ]
