# Generated by Django 3.2.5 on 2022-06-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0003_auto_20220624_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leverancier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvr_Naam', models.CharField(help_text='Naam Leverancier', max_length=45, verbose_name='Naam')),
                ('lvr_Notities', models.TextField(blank=True, null=True, verbose_name='Notities')),
            ],
            options={
                'verbose_name_plural': 'Leveranciers',
                'ordering': ('lvr_Naam',),
            },
        ),
        migrations.AlterModelOptions(
            name='activiteit',
            options={'verbose_name': 'Activiteit, Project, Lezing, enz.', 'verbose_name_plural': 'Activiteiten'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='cnt_Activiteit',
            field=models.ManyToManyField(blank=True, help_text='Activiteiten waaraan dit contact deelneemt; ', to='drzData.Activiteit', verbose_name='Activiteiten'),
        ),
        migrations.AddField(
            model_name='nummer',
            name='Leverancier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.leverancier'),
        ),
    ]
