# Generated by Django 3.0.5 on 2022-06-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0003_auto_20220610_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='Groep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drzData.Groep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nummer',
            name='Groep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drzData.Groep'),
            preserve_default=False,
        ),
    ]
