# Generated by Django 3.2.5 on 2022-06-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0004_auto_20220624_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aci_Naam', models.CharField(max_length=85, verbose_name='Naam')),
                ('aci_Omschr', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
                ('aci_Status', models.CharField(blank=True, choices=[('O', 'Open'), ('U', 'In Uitvoering'), ('V', 'Volbracht')], default='O', max_length=1, null=True, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_Acties',
            field=models.ManyToManyField(blank=True, help_text='Acties (open) mbt dit contact; ', to='drzData.Actie', verbose_name='Acties'),
        ),
    ]
