# Generated by Django 3.2.5 on 2022-06-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0005_auto_20220624_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bezoekreden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bzr_Naam', models.CharField(max_length=120, verbose_name='Reden')),
                ('bzr_Omschr', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
            ],
            options={
                'verbose_name_plural': 'Bezoekredenen',
            },
        ),
        migrations.AlterModelOptions(
            name='actie',
            options={'verbose_name_plural': 'Acties'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='cnt_Acties',
            field=models.ManyToManyField(blank=True, help_text='Acties (open) mbt dit contact; ', related_query_name='acties_related', to='drzData.Actie', verbose_name='Acties'),
        ),
        migrations.AlterField(
            model_name='vraag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WinkelBezoek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbz_TijdStip', models.DateTimeField(blank=True, null=True, verbose_name='Tijdstip van bezoek')),
                ('wbz_Bezoeken', models.ManyToManyField(blank=True, to='drzData.Bezoekreden', verbose_name='Bezoekreden(en)')),
            ],
            options={
                'verbose_name_plural': 'Winkelbezoeken',
                'ordering': ('wbz_TijdStip',),
            },
        ),
    ]
