# Generated by Django 3.2.5 on 2022-06-26 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0006_auto_20220625_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_Naam', models.CharField(help_text='Naam Exposant', max_length=45, verbose_name='Naam')),
                ('exp_Notities', models.TextField(blank=True, null=True, verbose_name='Notities')),
            ],
            options={
                'verbose_name_plural': 'Exposanten',
                'ordering': ('exp_Naam',),
            },
        ),
        migrations.AddField(
            model_name='adres',
            name='Leverancier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.leverancier'),
        ),
        migrations.AddField(
            model_name='winkelbezoek',
            name='wbz_Notities',
            field=models.TextField(blank=True, null=True, verbose_name='Notities'),
        ),
        migrations.AddField(
            model_name='adres',
            name='Exposant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.exposant'),
        ),
        migrations.AddField(
            model_name='nummer',
            name='Exposant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.exposant'),
        ),
    ]
