# Generated by Django 3.0.5 on 2022-06-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0006_adresgroep_nummergroep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adres',
            name='Groep',
        ),
        migrations.RemoveField(
            model_name='nummer',
            name='Groep',
        ),
    ]
