# Generated by Django 3.0.5 on 2022-06-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0007_auto_20220611_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woninggegevens',
            fields=[
                ('wng_TypeWoning', models.CharField(blank=True, choices=[('T', 'Tussenwoning'), ('H', 'Hoekwoning'), ('2', '2-1 Kap'), ('V', 'Vrijstaand'), ('A', 'Appartement')], max_length=1, null=True, verbose_name='Type Woning')),
                ('wng_Bouwjaar', models.CharField(blank=True, choices=[('V', 'Voor 1980'), ('T', '1980 - 2000'), ('N', 'Na 2000')], max_length=1, null=True, verbose_name='Bouwjaar')),
                ('wng_Bewoning', models.CharField(blank=True, choices=[('H', 'Verhuur'), ('V', 'VVE'), ('E', 'Eigendom')], max_length=1, null=True, verbose_name='Type bewoning')),
            ],
        ),
        migrations.AlterModelOptions(
            name='groep',
            options={'verbose_name': 'Groep', 'verbose_name_plural': 'Organisaties, Instanties, Bedrijven, enz.'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='cnt_Groepen',
            field=models.ManyToManyField(blank=True, help_text='Groepen waaronder dit contact valt; ', to='drzData.Groep', verbose_name='Groep(en)'),
        ),
        migrations.AlterField(
            model_name='groep',
            name='grp_GroupNm',
            field=models.CharField(max_length=45, verbose_name='Groep'),
        ),
        migrations.AlterField(
            model_name='groep',
            name='grp_Website',
            field=models.CharField(blank=True, help_text='Plak hier de url van website van groep', max_length=240, null=True, verbose_name='Website'),
        ),
    ]
