# Generated by Django 3.0.5 on 2022-06-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0008_auto_20220614_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vraag',
            fields=[
                ('vrg_TypeVraag', models.CharField(blank=True, choices=[('I', 'Info'), ('A', 'Advies'), ('O', 'Offerte')], max_length=1, null=True, verbose_name='Type vraag')),
                ('vrg_OnderwerpVraag', models.CharField(blank=True, choices=[('Ea', 'Energie algemeen'), ('Eiv', 'Energie isolatie vloer'), ('Eim', 'Energie isolatie muur'), ('Eig', 'Energie isolatie glas'), ('Eid', 'Energie isolatie dak'), ('Ev', 'Energie verwarming'), ('Eo', 'Energie opwekking'), ('C', 'Circulair'), ('G', 'Groen'), ('O', 'Overig')], max_length=3, null=True, verbose_name='Onderwerp vraag')),
                ('vrg_StatusVraag', models.CharField(blank=True, choices=[('B', 'Beantwoord'), ('O', 'Onbeantwoord'), ('U', 'Wordt uitgezocht')], max_length=1, null=True, verbose_name='Status vraag')),
                ('vrg_Tekst', models.TextField(blank=True, null=True, verbose_name='Notities')),
            ],
        ),
    ]
