# Generated by Django 3.0.5 on 2022-06-14 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drzData', '0009_vraag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vraag',
            options={'verbose_name_plural': 'Vragen'},
        ),
        migrations.AlterModelOptions(
            name='woninggegevens',
            options={'verbose_name_plural': 'Woninggegevens'},
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_DatVastlegging',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tijdstip van notatie'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_Vastlegger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='Genoteerd door', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vraag',
            name='vrg_Tekst',
            field=models.TextField(blank=True, null=True, verbose_name='Tekst vraag'),
        ),
    ]
