# Generated by Django 3.0.5 on 2022-06-15 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drzData', '0010_auto_20220614_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cnt_DatVastlegging',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tijdstip van notatie'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cnt_Vastlegger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='Genoteerd door', to=settings.AUTH_USER_MODEL, verbose_name='Vastlegger'),
        ),
        migrations.AlterField(
            model_name='vraag',
            name='Contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.Contact'),
        ),
        migrations.AlterField(
            model_name='woninggegevens',
            name='Contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.Contact'),
        ),
    ]
