# Generated by Django 3.0.5 on 2022-06-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0011_auto_20220615_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vraag',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
