# Generated by Django 3.0.5 on 2022-06-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0013_auto_20220615_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='woninggegevens',
            name='Contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drzData.Contact'),
        ),
        migrations.AddField(
            model_name='woninggegevens',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
